DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS configs;
DROP TABLE IF EXISTS bots;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL
);

CREATE TABLE configs (
    user_id INTEGER PRIMARY KEY,
    API_KEY TEXT DEFAULT '',
    API_SECRET_KEY TEXT DEFAULT '',
    API_PASSPHRASE TEXT DEFAULT '',
    TRADING_PAIR TEXT DEFAULT 'ETH-USDT-SWAP',
    LEVERAGE INTEGER DEFAULT 10,
    BOT_POLL_INTERVAL INTEGER DEFAULT 5,
    MAX_ORDERS_IN_CYCLE INTEGER DEFAULT 5,
    DRY_RUN_MODE BOOLEAN DEFAULT TRUE,
    LONG_ENABLED BOOLEAN DEFAULT TRUE,
    LONG_MARGIN_PER_ORDER_PERCENTAGE REAL DEFAULT 0.05,
    LONG_TAKE_PROFIT_PERCENTAGE REAL DEFAULT 0.001,
    LONG_ENTRY_PRICE_FALL_PERCENTAGE REAL DEFAULT 0.005,
    SHORT_ENABLED BOOLEAN DEFAULT TRUE,
    SHORT_MARGIN_PER_ORDER_PERCENTAGE REAL DEFAULT 0.05,
    SHORT_TAKE_PROFIT_PERCENTAGE REAL DEFAULT 0.001,
    SHORT_ENTRY_PRICE_RISE_PERCENTAGE REAL DEFAULT 0.005,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE bots (
    user_id INTEGER PRIMARY KEY,
    status TEXT NOT NULL DEFAULT 'Stopped',
    pid INTEGER,
    temp_dir TEXT,
    log_file TEXT,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

